// --------------------------------------------------------------------
// <copyright file="MakeGiftController.cs" company="Ellucian">
//     Copyright 2020 - 2023 Ellucian Company L.P. and its affiliates.
// </copyright>
// --------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using SelfService.Filters;

namespace SelfService.Controllers
{
    /// <summary>
    /// Controller with views for Make a Gift.
    /// </summary>
    /// <seealso cref="Controller" />
    [TypeFilter(typeof(SessionExpiredAttribute), Arguments = new object[] { false, true })]
    public class MakeGiftController : Controller
    {
        /// <summary>
        /// Donations View.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        [HttpGet]
        [TypeFilter(typeof(RoleAuthorizeAttribute), Arguments = new object[] { new string[] { "MakeGiftId" } })]
        public ActionResult MakeGift()
        {
            if (TempData[Constants._paymentTransactionTempData] != null)
                ViewBag.PaymentTransaction = TempData[Constants._paymentTransactionTempData];

            return View();
        }
    }
}